from pathlib import Path
p=Path('/mnt/data/revise/index.html')
s=p.read_text()
s=s.replace("let session=null, routeProject=null, state={projects:[],blocks:[],scenes:[],tab:'script',name:'',saving:false};", "let session=null, routeProject=null, state={projects:[],blocks:[],scenes:[],tab:'script',name:'',saving:false,scriptSceneId:null};")
s=s.replace("const {data:b}=await sb.from('script_blocks').select('*').eq('project_id',id).order('position');state.blocks=b||[];", "const {data:b}=await sb.from('script_blocks').select('*').eq('project_id',id).order('position');state.blocks=b||[];")
old="""function scriptView(){return `<section class=\"card\"><div class=\"section-head\"><div><h2>Script</h2><p>Blok script tersimpan langsung ke Supabase Database.</p></div><div class=\"row\"><button class=\"btn\" data-add=\"action\">＋ Action</button><button class=\"btn\" data-add=\"dialog\">＋ Dialog</button><button class=\"btn\" data-add=\"expression\">＋ Expression</button><button class=\"btn\" data-add=\"shot\">＋ Shot</button><button class=\"btn primary\" id=\"saveBlocks\">${state.saving?'Saving…':'Save'}</button></div></div><div class=\"script\">${state.blocks.map(b=>`<div class=\"block\"><div class=\"block-label\">${esc(b.type)}${b.meta?' · '+esc(b.meta):''}</div><textarea data-block=\"${b.id}\">${esc(b.content)}</textarea><button class=\"icon-btn block-delete\" data-delete=\"${b.id}\">${icon('trash',14)}</button></div>`).join('')}</div>${!state.blocks.length?'<div class=\"empty-inline\">Belum ada blok script. Tambahkan Action, Dialog, Expression, atau Shot.</div>':''}</section>`}
  function bindScript(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addBlock(b.dataset.add));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteBlock(b.dataset.delete));document.querySelectorAll('[data-block]').forEach(t=>t.oninput=()=>{const x=state.blocks.find(v=>v.id===t.dataset.block);if(x)x.content=t.value});$('saveBlocks').onclick=saveBlocks}
  async function addBlock(type){const position=state.blocks.length;const {data,error}=await sb.from('script_blocks').insert({project_id:routeProject,type,content:'Tulis isi di sini…',position}).select('*').single();if(error)return err(error);state.blocks.push(data);workspaceView()}
  async function saveBlocks(){state.saving=true;workspaceView();const {error}=await sb.from('script_blocks').upsert(state.blocks.map((b,i)=>({id:b.id,project_id:routeProject,type:b.type,content:b.content,meta:b.meta,position:i})));state.saving=false;workspaceView();if(error)return err(error);toast('Script tersimpan.')}
  async function deleteBlock(id){const {error}=await sb.from('script_blocks').delete().eq('id',id);if(error)return err(error);state.blocks=state.blocks.filter(x=>x.id!==id);workspaceView()}
"""
new="""function scriptView(){
  if(!state.scriptSceneId && state.scenes.length) state.scriptSceneId=state.scenes[0].id;
  const scene=state.scenes.find(s=>s.id===state.scriptSceneId)||state.scenes[0];
  const blocks=(state.blocks||[]).filter(b=>b.scene_id===scene?.id);
  return `<section class=\"card\"><div class=\"section-head\"><div><div class=\"eyebrow\">SCRIPT PER SCENE</div><h2>Script Produksi</h2><p>Setiap scene memiliki daftar talent dan detail action, ekspresi, dialog, serta deskripsinya sendiri.</p></div><div class=\"row\"><button class=\"btn primary\" id=\"addScriptScene\">＋ Scene Baru</button></div></div>
  <div class=\"scene-tabs\">${state.scenes.map((s,i)=>`<button type=\"button\" class=\"scene-tab ${s.id===scene?.id?'active':''}\" data-script-scene=\"${s.id}\"><span>SCENE ${i+1}</span>${esc(s.name)}</button>`).join('')}</div>
  ${scene?`<div class=\"script-scene-head\"><div><div class=\"eyebrow\">SCENE ${state.scenes.indexOf(scene)+1}</div><input class=\"scene-name\" id=\"scriptSceneName\" value=\"${esc(scene.name)}\" placeholder=\"Nama scene\"><textarea class=\"scene-desc\" id=\"scriptSceneDesc\" placeholder=\"Deskripsi scene…\">${esc(scene.description||'')}</textarea></div>${state.scenes.length>1?`<button class=\"btn ghost danger\" id=\"deleteScriptScene\">${icon('trash',15)} Hapus Scene</button>`:''}</div>
  <div class=\"section-head script-toolbar\"><div><h2>Talent & Script</h2><p>Tambahkan satu blok untuk setiap talent atau momen dalam scene ini.</p></div><div class=\"row\"><button class=\"btn\" id=\"addTalentScript\">＋ Tambah Talent / Script</button><button class=\"btn primary\" id=\"saveBlocks\">${state.saving?'Saving…':'Simpan Script'}</button></div></div>
  <div class=\"script-cards\">${blocks.map((b,i)=>`<article class=\"script-card\"><div class=\"script-card-head\"><div><span class=\"script-number\">${String(i+1).padStart(2,'0')}</span><strong>Talent ${i+1}</strong></div><button class=\"icon-btn\" data-delete=\"${b.id}\" aria-label=\"Hapus script\">${icon('trash',14)}</button></div><div class=\"script-fields\"><label><span>Nama Talent</span><input data-field=\"talent_name\" data-block=\"${b.id}\" value=\"${esc(b.talent_name||'')}\" placeholder=\"Nama talent…\"></label><label><span>Action</span><textarea data-field=\"action\" data-block=\"${b.id}\" placeholder=\"Apa yang dilakukan talent?\">${esc(b.action||'')}</textarea></label><label><span>Ekspresi</span><textarea data-field=\"expression\" data-block=\"${b.id}\" placeholder=\"Ekspresi / mood talent…\">${esc(b.expression||'')}</textarea></label><label><span>Dialog</span><textarea data-field=\"dialog\" data-block=\"${b.id}\" placeholder=\"Dialog yang diucapkan…\">${esc(b.dialog||'')}</textarea></label><label class=\"wide\"><span>Deskripsi</span><textarea data-field=\"description\" data-block=\"${b.id}\" placeholder=\"Detail blocking, kamera, timing, wardrobe, atau catatan produksi…\">${esc(b.description||'')}</textarea></label></div></article>`).join('')}</div>${!blocks.length?'<div class=\"empty-inline\">Belum ada script di scene ini. Klik <b>Tambah Talent / Script</b> untuk mulai.</div>':''}</div>`:'<div class=\"empty\">Belum ada scene. Klik Scene Baru untuk membuat scene pertama.</div>'}</section>`}
  function bindScript(){
    $('addScriptScene')?.addEventListener('click',addScene);
    document.querySelectorAll('[data-script-scene]').forEach(b=>b.onclick=()=>{state.scriptSceneId=b.dataset.scriptScene;workspaceView()});
    document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteBlock(b.dataset.delete));
    document.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>{const x=state.blocks.find(v=>v.id===el.dataset.block);if(x)x[el.dataset.field]=el.value});
    $('addTalentScript')?.addEventListener('click',addTalentScript);
    $('saveBlocks')?.addEventListener('click',saveBlocks);
    $('scriptSceneName')?.addEventListener('blur',e=>updateSceneMeta(state.scriptSceneId,'name',e.target.value));
    $('scriptSceneDesc')?.addEventListener('blur',e=>updateSceneMeta(state.scriptSceneId,'description',e.target.value));
    $('deleteScriptScene')?.addEventListener('click',()=>deleteScene(state.scriptSceneId));
  }
  async function addTalentScript(){const sceneId=state.scriptSceneId||state.scenes[0]?.id;if(!sceneId)return toast('Buat scene terlebih dahulu.');const position=state.blocks.filter(b=>b.scene_id===sceneId).length;const payload={project_id:routeProject,scene_id:sceneId,type:'talent',talent_name:'',action:'',expression:'',dialog:'',description:'',content:'',position};const {data,error}=await sb.from('script_blocks').insert(payload).select('*').single();if(error)return err(error);state.blocks.push(data);workspaceView();setTimeout(()=>document.querySelector('[data-field=talent_name]:last-of-type')?.focus(),50)}
  async function saveBlocks(){state.saving=true;workspaceView();const rows=state.blocks.map(b=>({id:b.id,project_id:routeProject,scene_id:b.scene_id,type:b.type||'talent',talent_name:b.talent_name||'',action:b.action||'',expression:b.expression||'',dialog:b.dialog||'',description:b.description||'',content:b.content||'',meta:b.meta||'',position:b.position||0}));const {error}=await sb.from('script_blocks').upsert(rows);state.saving=false;workspaceView();if(error)return err(error);toast('Script tersimpan.')}
  async function deleteBlock(id){const {error}=await sb.from('script_blocks').delete().eq('id',id);if(error)return err(error);state.blocks=state.blocks.filter(x=>x.id!==id);workspaceView()}
"""
if old not in s:
    raise SystemExit('old script section not found')
s=s.replace(old,new)
p.write_text(s)
